Updatable poseidon
HorizenOfficial/zendoo-mc-cryptolib pull request #27
Opened 2020-06-23 11:39 UTC by DanieleDiBenedetto

2020-06-23 11:40 UTC, DanieleDiBenedetto commented on src/ginger_calls.rs
> +// PoseidonHash("This represents an empty Merkle Root for a MNT4753PoseidonHash based Merkle Tree.") padded with 0s
To remove after changing dependecies to point against GingerLib's development

2020-06-23 11:44 UTC, DanieleDiBenedetto commented on Cargo.lock
> +source = "git+https://github.com/ZencashOfficial/ginger-lib.git?rev=981a62cb7f0205a4bde05640e3b17675df069243#981a62cb7f0205a4bde05640e3b17675df069243"
Change to last commit on GingerLib's development branch, when corresponding PR in GingerLib will be approved and merged in development branch.

2020-06-23 11:45 UTC, DanieleDiBenedetto commented on Cargo.toml
> +rev = "981a62cb7f0205a4bde05640e3b17675df069243"
Change to last commit on GingerLib's development branch, when corresponding PR in GingerLib will be approved and merged in development branch.

2021-05-03 14:01 UTC, albertog78 requested changes

2021-05-04 13:09 UTC, merged