Added missing sc_id field to cert prover/verifier/hash
HorizenOfficial/zendoo-mc-cryptolib pull request #41
Opened 2021-06-08 09:04 UTC by DanieleDiBenedetto

2021-06-14 08:26 UTC, alsala requested changes

2021-06-14 08:26 UTC, alsala commented on mc_test/mcTestCall.cpp
> +    field_t* sc_id_f = zendoo_deserialize_field(sc_id.data(), &ret_code);
Add the 'free' call at the end of the usage

2021-06-22 09:56 UTC, albertog78 approved these changes

2021-07-01 13:36 UTC, alsala approved these changes

2021-07-06 15:12 UTC, merged