As/csw proof param constant
HorizenOfficial/zendoo-mc-cryptolib pull request #50
Opened 2021-08-27 13:15 UTC by alsala

related to zend_oo PR #179

2021-08-30 09:19 UTC, DanieleDiBenedetto requested changes

2021-08-30 09:19 UTC, DanieleDiBenedetto commented on examples/sampleCalls.cpp
> +        create_verify_csw_proof(false, false, proof_path, pk_path, vk_path, true);
Can we add another test case "Proof Verifier: CSWNoConst - Coboundary Marlin" and pass the last flag to false (like I did for Cert) ?

2021-08-30 09:19 UTC, DanieleDiBenedetto commented on examples/sampleCalls.cpp
> +        create_verify_csw_proof(false, false, proof_path, pk_path, vk_path, true);
Can we add another test case "Proof Verifier: CSWNoConst -Darlin" and pass the last flag to false (like I did for Cert) ?

2021-08-30 10:01 UTC, i-Alex requested changes

2021-08-30 10:04 UTC, DanieleDiBenedetto commented on src/mc_test_circuits/csw.rs
> +    let remaining_constraints = if constant_present { (num_constraints - 1)/8 } else { (num_constraints - 1)/4 };
yes the logic it's the same

2021-08-30 10:05 UTC, DanieleDiBenedetto commented on src/mc_test_circuits/csw.rs
> +                constant: None,
When creating the keys, constant doesn't have a value so it's ok that it's None.

2021-09-02 09:47 UTC, DanieleDiBenedetto approved these changes

2021-09-02 10:22 UTC, i-Alex approved these changes

2021-09-02 14:27 UTC, albertog78 approved these changes

2021-10-06 14:10 UTC, merged