Remove fixed version from dependencies
HorizenOfficial/zendoo-mc-cryptolib pull request #67
Opened 2023-01-27 15:25 UTC by nicholas-mainardi

This PR removes the `Cargo.lock` from the list of the committed files and the fixed versions employed in `Cargo.toml` files for all dependencies

2023-01-30 14:56 UTC, DanieleDiBenedetto commented on Cargo.toml
>  rayon = {version = "1" }
Let's specify rayon and rayon-core here maybe as in the other repos ?

2023-01-30 14:56 UTC, DanieleDiBenedetto approved these changes

2023-06-29 12:40 UTC, la10736 requested changes
Please recover Cargo.toml and just remove = from Cargo.lock

2023-06-29 13:46 UTC, la10736 approved these changes

2023-06-29 15:20 UTC, merged